name: CI
on:
  push:
    branches:
      - main
      - dev-0.4
  pull_request:
    branches:
      - main
      - dev-0.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: g++
          cmake: true

      - name: Install Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake # Om cmake inte redan är installerat

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

