name: CI
on:
  push:
    branches:
      - main
      - dev-0.4
  pull_request:
    branches:
      - main
      - dev-0.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v2  # Uppdaterad version
        with:
          compiler: g++

      - name: Cache CMake files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/CMake
            build/
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Build with CMake
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

