name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@latest  # Se till att kolla versionen
      with:
        compiler: g++

    - name: Cache CMake files
      uses: actions/cache@v3  # Uppdaterad till v3
      with:
        path: /tmp/.build-cache
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Install dependencies
      run: sudo apt-get install -y clang-format clang-tidy
